ALTER TABLE CageVisits
	ADD CONSTRAINT c FOREIGN KEY (cageID) 
	REFERENCES Cages(cageID);
ALTER TABLE CageVisits
	ADD CONSTRAINT d FOREIGN KEY (memberID)
	REFERENCES Members(memberID)
	ON UPDATE CASCADE;
